Allow add_XXX methods to act as constructors
aiplan4eu/unified-planning pull request #141
Opened 2022-04-30 23:45 UTC by arbimo

This is a quick and dirty experiment for an API improvement to limit the boilerplate when creating elements that must be added to the problem and reused in other parts of the problem definition (notably objects, fluents, ...).

Manipulating such elements is always a two step process: creating the element and then adding it to the `Problem`.

```python
# Previous syntax (still supported)
pb = Problem()
Item = UserType('Item')
heavy = Fluent('heavy', Item)
o = Object('o', Item)
pb.add_object(o)
pb.add_fluent(heavy)
pb.set_initial_value(heavy(o), True)
```

This is PR is a proposal for `Problem.add_XXX` methods to support to kinds of input:
 - the already constructed element (e.g. an `Object` instance)
 - the parameters to the element's constructor, used to initialize it (e.g. the `name` and `typename` of the `Object` constructor)

Regardless of its input, it returns the element to enable its future usage.
In addition to the previous one, this allows to support the more straightforward syntax:

```python
Item = UserType('Item')
pb = Problem()
o = pb.add_object('o', Item)
heavy = pb.add_fluent('heavy', Item)
pb.set_initial_value(heavy(o), True)
```

At this point, this PR is not battle tested but is only meant to check if there is interest in this API change. This is a pattern that I use in #140 for building tasks and subtask an later referencing them.

2022-05-02 13:52 UTC, mikand commented
I like this idea very much! It simplifies the creation of problems without sacrificing retro-compatibility and the flexibility of having reusable Fluents and Objects.

@alvalentini @Framba-Luca what do you think? Can you see any criticality?

2022-05-05 13:24 UTC, alvalentini requested changes
@arbimo @mikand I like the proposal, I think it can be useful!

I added a few comment in the code.

2022-05-05 13:24 UTC, alvalentini commented on unified_planning/model/problem.py
> +                   typename: 'up.model.types.Type' = None) -> 'up.model.fluent.Fluent':
```suggestion
    def add_fluent(self, fluent_or_name: Union['up.model.fluent.Fluent', str], 
                   typename: 'up.model.types.Type' = None, *,
                   default_initial_value: Union['up.model.fnode.FNode', 'up.model.object.Object',
                   bool, int, float, Fraction] = None
                   **kwargs: 'up.model.types.Type') -> 'up.model.fluent.Fluent':
```

2022-05-05 13:24 UTC, alvalentini commented on unified_planning/model/problem.py
> +            assert len(args) == 0
```suggestion
            assert len(kwargs) == 0 and typename is None
```

2022-05-05 13:24 UTC, alvalentini commented on unified_planning/model/problem.py
> +            fluent = up.model.fluent.Fluent(fluent_or_name, typename, *args)
```suggestion
            fluent = up.model.fluent.Fluent(fluent_or_name, typename, env=self.env, **kwargs)
```

2022-05-12 07:53 UTC, alvalentini commented on unified_planning/model/problem.py
> +                   bool, int, float, Fraction] = None
@arbimo I forgot the comma in my last suggestion:
```suggestion
                   bool, int, float, Fraction] = None,
```

2022-05-12 11:42 UTC, arbimo commented
@alvalentini Thanks for the review, I added the suggestions (incorporating your suggestions).

The main downside of this proposal is that the function' signature does not immediately convey what it does. Hence I documented the two methods. The docstrings contain examples that will be automatically checked on CI (I enabled doctest in pytest).

2022-05-12 11:51 UTC, Framba-Luca reviewed
I really like the idea and think it is very useful and allows faster coding and less prone to errors due to the user forgetting to add the object/fluent to the problem!

For coherence do you plan to do the same for the actions? The use would be much less and the implementation more problematic, due to the difference between InstantaneousAction and DurativeAction, but it's a point worth thinking about.

I also left 1 very minor comment in the code.

2022-05-12 11:51 UTC, Framba-Luca commented on unified_planning/model/problem.py
> +            assert len(kwargs) == 0 and typename is None
Here I would raise a meaningful Exception, so that the code is more user-fail-friendly

2022-05-12 11:51 UTC, Framba-Luca commented on unified_planning/model/problem.py
> +            assert typename is None
Same

2022-05-12 11:51 UTC, Framba-Luca commented on unified_planning/model/problem.py
> +            assert typename is not None, "Missing type of the object"
Same

2022-05-12 15:14 UTC, Framba-Luca reviewed
Perfect, makes sense for the Actions. 

Ye, our discrepancy about "assert or exception" originated from the fact that I prefer using exceptions also for user errors and input validation.

2022-05-13 09:45 UTC, alvalentini approved these changes

2022-05-13 16:52 UTC, merged