Implementation of a Simulator
aiplan4eu/unified-planning pull request #156
Opened 2022-06-10 18:21 UTC by Framba-Luca

2022-06-13 08:08 UTC, mikand requested changes
@Framba-Luca Good work! The general PR is well thought, I left some comments for improvements, but we are close!

2022-06-13 08:08 UTC, mikand commented on unified_planning/model/state.py
> +    max_ancestors: int = 3
Document this filed. Moreover use UPPER_CASE for constants. Finally, 3 is a very low value, I would go with `20`

2022-06-15 07:54 UTC, mikand approved these changes

2022-06-15 11:41 UTC, alvalentini requested changes

2022-06-15 11:41 UTC, alvalentini commented on unified_planning/engines/mixins/simulator.py
> +    def __init__(self, problem: 'up.model.AbstractProblem', **params) -> None:
`**params` should not be a parameter of this Mixin

2022-06-15 11:41 UTC, alvalentini commented on unified_planning/engines/mixins/simulator.py
> +        raise NotImplementedError
```suggestion
        self._problem = problem
```

and update the SequentialSimulator accordingly.

2022-06-15 11:41 UTC, alvalentini commented on unified_planning/engines/mixins/simulator.py
> +class Simulator:
`SimulatorMixin`?

2022-06-16 13:46 UTC, alvalentini requested changes

2022-06-16 13:46 UTC, alvalentini commented on unified_planning/engines/sequential_simulator.py
> +        self._problem = cast(up.model.Problem, self._problem)
Here you can use an assert
```suggestion
        assert isinstance(up.model.Problem, self._problem)
```

and you can move it after the check at lines 60-61

2022-06-16 15:18 UTC, mikand requested changes
There are some changes that are needed (and were highlighted in yesterday's WP3 meeting)

2022-06-16 15:18 UTC, mikand commented on unified_planning/engines/sequential_simulator.py
> +        map = cast(Callable[[ActionInstance], ActionInstance], self._grounding_result.map_back_action_instance)
`map` is a bad name, because it is a reserved keyword in Python. It works because you can redefine even built-ins, but it is a bad practice

2022-06-16 15:18 UTC, mikand commented on unified_planning/engines/sequential_simulator.py
> +        map = cast(Callable[[ActionInstance], ActionInstance], self._grounding_result.map_back_action_instance)
Why is this cast needed?

2022-06-16 15:18 UTC, mikand commented on unified_planning/engines/sequential_simulator.py
> +            if cond.is_bool_constant() and cond.bool_constant_value():
KISS
```suggestion
            if (not e.is_conditional()) or self._se.evaluate(e.condition, state).is_true():
```

2022-06-16 15:18 UTC, mikand commented on unified_planning/engines/sequential_simulator.py
> +                    updated_values[e.fluent] = em.auto_promote(f_eval.constant_value() - v_eval.constant_value())[0]
Same

2022-06-16 15:18 UTC, mikand commented on unified_planning/model/state.py
> +            retval = f'{retval}\n{str(current_instance._values)}'
This is very inefficient in python, because strings are immutable. Use a list and then concatenate it

2022-06-16 15:18 UTC, mikand commented on unified_planning/model/state.py
> +    def _has_value(self, value: 'up.model.FNode') -> bool:
```suggestion
    def _has_local_value(self, value: 'up.model.FNode') -> bool:
```

2022-06-17 13:14 UTC, merged