Infix notation
aiplan4eu/unified-planning pull request #177
Opened 2022-06-23 09:28 UTC by Framba-Luca

2022-06-23 09:55 UTC, mikand approved these changes
@Framba-Luca Excellent! I added a minor suggestion, for the rest, this looks OK.

2022-06-23 09:55 UTC, mikand commented on unified_planning/model/fnode.py
> +        return get_env().expression_manager.Minus(0, self)
I think we need to add `__pos__`, and `__invert__` (see https://www.oreilly.com/library/view/python-in-a/0596001886/re22.html)

2022-06-28 15:55 UTC, mikand requested changes
@Framba-Luca Excellent work! I left few very minor comments to fix. In addition I would add a test that triggers the exceptions when one tries to combine two different environments

2022-06-28 15:55 UTC, mikand commented on unified_planning/model/object.py
> +    def __init__(self, name: str, typename: 'unified_planning.model.types.Type', env: Environment = None):
I think this should be `Optional`, no?

2022-06-28 15:55 UTC, mikand commented on unified_planning/model/parameter.py
> +        self._env = get_env(env)
No need o do `get_env`, the `env` parameter is non-optional here

2022-06-28 15:55 UTC, mikand commented on unified_planning/model/variable.py
> +    def __init__(self, name: str, typename: 'unified_planning.model.types.Type', env: Environment = None):
should be `Optional`

2022-06-28 17:56 UTC, Framba-Luca commented on unified_planning/model/expression.py
> +from pytest import param
vscode automatic import... My bad

2022-06-29 09:11 UTC, mikand commented on unified_planning/model/parameter.py
> +    def __init__(self, name: str, typename: 'up.model.types.Type', env: Environment):
@Framba-Luca Sorry, my bad in the previous code review: can tou rever this change and leave environemnt as `Optional`?

2022-06-29 09:14 UTC, mikand approved these changes
@Framba-Luca two very minor things before merging

2022-06-29 09:14 UTC, mikand commented on unified_planning/model/problem.py
> +            assert goal.environment == self._env, 'timed_goal does not have the same environment of the problem'
```python
assert isinstance(goal, bool) or goal.environment == self._env, '...'
```

2022-06-29 12:01 UTC, merged