Portfolio Interface
aiplan4eu/unified-planning pull request #291
Opened 2022-12-16 10:18 UTC by Framba-Luca

Created a PortfolioSelectorMixin, created a PortfolioSelector Operation Mode and documented

2022-12-16 13:38 UTC, mikand requested changes
@Framba-Luca Excellent work. I left some very minor comments, then we can merge!

2022-12-16 13:38 UTC, mikand commented on unified_planning/engines/engine.py
> +class OperationMode(Enum):
Missing doc

2022-12-16 13:38 UTC, mikand commented on unified_planning/engines/factory.py
> +        engine_kind: "OperationMode",
At this point I would rename this:
```suggestion
        operation_mode: "OperationMode",
```

2022-12-16 13:38 UTC, mikand commented on unified_planning/engines/factory.py
> +        operation_mode: Optional["OperationMode"] = None,
I would rename this, for the inetrnal methods, while for the public ones it's OK: 
```suggestion
        target_operation_mode: Optional["OperationMode"] = None,
```

2022-12-16 13:38 UTC, mikand commented on unified_planning/engines/factory.py
> +            operation_mode=operation_mode,
```suggestion
            target_operation_mode=operation_mode,
```

2023-01-05 10:31 UTC, alvalentini commented on unified_planning/engines/factory.py
> +    ) -> "up.engines.engine.Engine":
I think that other parameters could be useful, for example `optimality_guarantee` in case the operation mode is `OperationMode.ONESHOT_PLANNER`.

2023-01-10 16:58 UTC, mikand commented
@alvalentini @Framba-Luca After a bit of discussion, we decided to remove the `operation_mode` parameter from the `PortfolioSelector` OM to keep things simpler. Moreover we need to add the `optimality_guarantee` parameter to mimik the `OneshotPlanning` OM.

@alvalentini Can you do the fix and then merge?

2023-01-11 11:22 UTC, merged