Non constant boolean assignment
aiplan4eu/unified-planning pull request #365
Opened 2023-03-23 11:34 UTC by Framba-Luca

This PR adds the effects kind that discriminates between constant and non constant assignments, and fixes the PDDLWriter when writing non-constant boolean assignments

2023-03-29 12:58 UTC, alvalentini requested changes

2023-03-29 12:58 UTC, alvalentini commented on unified_planning/model/problem.py
> +                    unused_fluents.difference_update(unused_fluents)
```suggestion
                    unused_fluents.clear()
```

2023-03-29 12:58 UTC, alvalentini commented on unified_planning/model/problem.py
> +                remove_used_fluents(a.duration.upper)
```suggestion
```

2023-03-29 12:58 UTC, alvalentini commented on unified_planning/model/problem.py
> +                    remove_used_fluents(e.condition)
```suggestion
                    remove_used_fluents(e.fluent, e.value, e.condition)
```

Same below

2023-03-29 13:43 UTC, Framba-Luca commented on unified_planning/model/problem.py
> +                    unused_fluents.difference_update(unused_fluents)
Ah yes, I fixed the one at line 318

2023-03-30 10:06 UTC, alvalentini commented on unified_planning/engines/pddl_planner.py
> +            problem, self._needs_requirements, rewrite_bool_assignment=True
```suggestion
            problem, self._needs_requirements, self._rewrite_bool_assignment
```

2023-04-20 13:07 UTC, roeger commented
Hi, I am not sure whether this is the right place for this comment but since this pull request should also enable the action-costs requirement for classical planners, maybe yes.

I tried to solve with the Fast Downward integration (including the changes from the pull request) a task that uses numeric fluents for determining action costs. This would already be covered by the :actions-costs requirement but the PDDLWriter also adds requirement :numeric-fluents, so Fast Downward refuses to attempt the task (on the PDDL level, not the problem kind level). Is it possible to narrow down the PDDLWriter to not include this requirement in such situations?

2023-04-20 13:47 UTC, alvalentini commented
@roeger thanks for highlight the point, you are right! Now the PDDLWriter should not add :numeric-fluents in these situations.

2023-04-21 16:22 UTC, merged