PDDLAnytimePlanner refactoring
aiplan4eu/unified-planning pull request #396
Opened 2023-05-05 14:13 UTC by Framba-Luca

2023-05-10 16:04 UTC, alvalentini requested changes

2023-05-10 16:04 UTC, alvalentini commented on unified_planning/test/pddl/enhsp.py
> -            self._options.extend(["-timeout", str(timeout)])
This part should be kept

2023-05-10 16:04 UTC, alvalentini commented on unified_planning/test/pddl/enhsp.py
>          self._options = ["-planner", "opt-hrmax"]
There is no need to keep this two options here now

2023-05-10 16:04 UTC, alvalentini commented on unified_planning/engines/pddl_anytime_planner.py
> +        TODO document this better
TODO

2023-05-15 09:53 UTC, alvalentini commented
@roeger @hstairs @IvanSerina 

This PR aims to implement a common PDDLAnytimePlanner to avoid code duplication between planning engines.

Any feedback?

2023-05-24 08:07 UTC, Framba-Luca commented on unified_planning/engines/pddl_anytime_planner.py
> +        raise NotImplementedError
To fix doc

2023-05-30 09:29 UTC, alvalentini approved these changes

2023-05-30 09:29 UTC, merged

2023-06-05 12:03 UTC, roeger commented
@alvalentini I just tried to use the new class in the Fast Downward integration but there is a situation, where I am not sure how to cover it. The anytime search in Fast Downward terminates without a timeout once the search space has been exhausted. If a plan has been found earlier, my integration previously returned the last found plan with status SOLVED_SATISFICING.

With the current implementation, I would have a sequence of intermediate plans that at some point stops without any final plan. Is this the user interface we want? If not, what's your advice?