Validator Tracing and TimeTriggeredValidator
aiplan4eu/unified-planning pull request #524
Opened 2023-11-17 16:56 UTC by mikand

In this PR we extend the internal sequential validation engine to return the sequence of states encountered by executing a sequential plan and we add support for validation (and tracing) of TimeTriggeredPlans

2023-11-19 07:33 UTC, karpase commented
Commenting just to say I would like to see this implemented - I have some experiments this could really help with.

2023-11-20 08:07 UTC, Framba-Luca commented
In pr #509 also happens a "transformation" of a temporal structure into a non-temporal one. After the merge of both there will most certainly be space for refactoring (that maybe can be considered also when designing the missing code).

2023-12-06 15:53 UTC, Framba-Luca requested changes
LGTM! :smiley:

I left 4 comments. 2 are minor code-level improvements, 1 I think it's a bug, the 4th one is just a note on the `SequentialValidator` `supported_kind`

2024-01-11 14:07 UTC, Framba-Luca approved these changes

2024-01-15 08:24 UTC, arbimo approved these changes
LGTM! I just added a small comment about an awkwardness in error handling.

2024-01-15 09:00 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
>              try:
You are right! Fixed it!

2024-01-15 09:56 UTC, arbimo commented on unified_planning/engines/plan_validator.py
>              try:
Thanks!  I'll merge it then ;)

2024-01-15 09:56 UTC, merged