Temporal adapted conditional effect remover
aiplan4eu/unified-planning pull request #54
Opened 2021-10-11 06:43 UTC by Framba-Luca

2021-10-11 10:08 UTC, mikand requested changes
There are some opportunities for refactoring, but it looks almost perfect! Good job @Framba-Luca

2021-10-11 10:08 UTC, mikand commented on upf/conditional_effects_remover.py
> +                new_problem.add_timed_effect(t, e)
Good point. I would go for the third option: raise an exception stating that it is not possible to remove all the conditional effects.

If we want to be precise, we could remove the conditional effects for boolean variables as follows:
```
when psi then v  := phi
```
can be converted into 
```
v := (psi and phi) or ((not psi) and v)
```

2021-10-12 07:09 UTC, Framba-Luca commented on upf/conditional_effects_remover.py
> +        new_action = DurativeAction(new_action_name, new_parameters, self._env)
Yes, definitely!

2021-10-15 08:51 UTC, alvalentini commented on upf/transformers/conditional_effects_remover.py
> +    def _check_and_simplify_conditions(self, action: DurativeAction) -> bool:
@Framba-Luca Can these methods be moved to the `Remover` class?

2021-10-15 14:10 UTC, merged