new feature (interpreted functions)
aiplan4eu/unified-planning pull request #626
Opened 2024-09-11 08:31 UTC by Ezpeon

2024-11-12 17:27 UTC, alvalentini requested changes
@Ezpeon I left a few comments

2024-11-12 17:27 UTC, alvalentini commented on unified_planning/engines/interpreted_functions_planner.py
> +
This method can be refactored a little bit. It is not needed to have two pieces of code that call the Compiler.

Something like this:
```python
start = time.time()
knowledge = {}
while True:
    if timeout is not None:
        timeout -= time.time() - start
        if timeout <= 0:
            return PlanGenerationResult(TIMEOUT, None, self.name)
    with InterpretedFunctionsRemover(knowledge) as if_remover:
        comp_res = if_remover.compile(problem)
    res = self.engine.solve(comp_res.problem, heuristic, timeout, output_stream)
    if res.status in up.engines.results.POSITIVE_OUTCOMES:
        plan = res.plan.replace_action_instances(comp_res.map_back_action_instance)
        if plan.kind == PlanKind.SEQUENTIAL_PLAN:
            validator = SequentialPlanValidator()
        elif plan.kind == PlanKind.TIME_TRIGGERED_PLAN:
            validator = TimeTriggeredPlanValidator()
        else:
            raise 
        validation_result = validator.validate(problem, plan)
        if validation_result.status == ValidationResultStatus.VALID:
            return PlanGenerationResult(res.status, plan, self.name, log_messages=res.log_messages)
        else:
            knowledge.update(validation_result.calculated_interpreted_functions)
    else:
        return PlanGenerationResult(res.status, None, self.name)
```

2024-11-15 14:30 UTC, alvalentini requested changes

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +            hasif = True
Is this still needed?

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +        return ret_val
You can revert this change

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +                    calculated_interpreted_functions=calculated_interpreted_functions,
You can directly get the calculated interpreted functions here and in all the cases where you return a ValidationResult with an INVALID status
```suggestion
                    calculated_interpreted_functions=simulator.get_knowledge(),
```

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +                        calculated_interpreted_functions = simulator.get_knowledge()
Not needed

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +            hasif = True
Not needed

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/plan_validator.py
> +                            calculated_interpreted_functions=se.if_values,
Add this also in the other cases where the status in INVALID

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/engines/sequential_simulator.py
> +    def get_knowledge(self):
```suggestion
    def get_interpreted_functions_values(self):
```

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/model/expression.py
> +
One empty line is enough

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/model/expression.py
> +
```suggestion
        left, right = self.auto_promote(left, right)
        if left.type.is_bool_type() and right.type.is_bool_type():
```

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/model/walkers/quantifier_simplifier.py
> +                result = self.memoization[key]
This is not needed anymore, right?

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/model/walkers/simplifier.py
> +            constantval = self.manager.ObjectExp((constantval))
```suggestion
            constantval = self.manager.Bool(constantval)
        elif expression.interpreted_function().return_type.is_int_type():
            constantval = self.manager.Int(constantval)
        elif expression.interpreted_function().return_type.is_real_type():
            constantval = self.manager.Real(Fraction(constantval))
        elif expression.interpreted_function().return_type.is_user_type():
            constantval = self.manager.ObjectExp(constantval)
```

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/model/walkers/simplifier.py
> +            return new_exp
```suggestion
            raise UPUnreachableCodeError
```

2024-11-15 14:30 UTC, alvalentini commented on unified_planning/shortcuts.py
> +
```suggestion
```

2025-12-19 08:37 UTC, alvalentini commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +        )
This is not needed since you redefine it at line 228
```suggestion
```

2025-12-19 09:07 UTC, Ezpeon commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +        )
yep I'll remove it, it was a leftover

2025-12-19 15:24 UTC, alvalentini requested changes

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/engines/sequential_simulator.py
> +        self._grounder = GrounderHelper(problem, prune_actions=False)
Why is this change needed?

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/test/examples/minimals.py
> +from typing import OrderedDict
leftover?

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +            # TODO clean up is no problems are found
TODO and commented code to remove

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +    def _expand_action(self, a, new_fluents, new_objects, if_known, is_unknown_fluents):
Here we can add typing and documentation

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +    def _clone_action_with_extras(
Same here: typing and documentation

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/engines/compilers/interpreted_functions_remover.py
> +    def _default_value_given_type(self, t, problem):
Here and below. Use docstring for documenting functions and methods

2025-12-19 15:24 UTC, alvalentini commented on unified_planning/test/examples/interpreted_functions_examples.py
> +# Copyright 2024 Unified Planning library and its maintainers
```suggestion
# Copyright 2024-2025 Unified Planning library and its maintainers
```

Check also other files

2026-01-09 16:11 UTC, alvalentini commented
@arbimo @roeger @hstairs 

In this PR, we extended expressions by introducing `InterpretedFunctions`, which can be used as nodes within expressions. An `InterpretedFunction` contains Python code that can be executed for evaluation. We also implemented a meta-engine capable of solving problems that include `InterpretedFunctions` within action durations, conditions, or effects. More details can be found in the paper "Planning and Scheduling with External Functions in the ExploDTwin project" available in the [IWPSS proceedings](https://drive.google.com/file/d/1eYmOW3EmDVMB7peDSNbqvWxKzfqyKuPh/view?usp=sharing).

Does anyone have time to review this PR?

2026-05-29 12:45 UTC, alvalentini commented
Hi @arbimo @roeger @hstairs! We are considering merging this PR into `master` by the end of next week. If you have time to review it or have any comments, feel free to share them before then.

2026-05-29 13:00 UTC, alvalentini approved these changes

2026-06-09 14:53 UTC, merged