Python printer
aiplan4eu/unified-planning pull request #89
Opened 2022-02-23 16:28 UTC by Framba-Luca

2022-02-23 17:25 UTC, mikand requested changes
@Framba-Luca very nice! I left just some minor commits

2022-02-23 17:25 UTC, mikand commented on unified_planning/io/python_writer.py
> +#TODO: remove old commentedcode if it is not needed anymore.
leftover?

2022-02-23 17:25 UTC, mikand commented on unified_planning/io/python_writer.py
> +        out.write('from unified_planning.shortcuts import *\n')
I would avoid this import, you should be able to create everything based on the `env` object and make everything reentrant, no? This makes the generated code much more reusable IMHO

2022-02-23 17:25 UTC, mikand commented on unified_planning/io/python_writer.py
> +        return 'BoolType()'
Better:
```suggestion
        return 'env.type_manager.BoolType()'
```

2022-02-23 17:25 UTC, mikand commented on unified_planning/io/python_writer.py
> +        return f'StartTiming({bound})'
I think you need to import these explicitly or use the full name `up.model.timing.StartTiming`

2022-02-25 10:15 UTC, Framba-Luca commented on unified_planning/io/python_writer.py
> +                out.write(f'type_{cast(_UserType, type).name()} = tm.UserType("{cast(_UserType, type).name()}")\n')
@mikand  I would love to, and it was my first try and also my hope. But it doesn't work :cry:

2022-02-28 09:51 UTC, alvalentini requested changes
@Framba-Luca  I added some minor comments.

2022-02-28 09:51 UTC, alvalentini commented on unified_planning/io/python_writer.py
> +    def print_domain(self): # TODO: find a better name
This TODO should be removed or fixed

2022-02-28 09:51 UTC, alvalentini commented on unified_planning/io/python_writer.py
> +    def write_domain(self, filename: str): # TODO: find a better name
Same here

2022-02-28 09:51 UTC, alvalentini commented on unified_planning/io/python_writer.py
> +        '''Prints to std output the PDDL domain.'''
Is it PDDL?

2022-02-28 09:51 UTC, alvalentini commented on unified_planning/io/python_writer.py
> +        '''Returns the PDDL domain.'''
Is it PDDL?

2022-02-28 09:51 UTC, alvalentini commented on unified_planning/model/problem.py
> +    def _initial_values_structure(self) -> Dict['up.model.fnode.FNode', 'up.model.fnode.FNode']:
This method is used outside the `Problem` class. We should remove the initial `_`.

I think also that `explicit_initial_values` could be a better name. What do you think?

2022-03-01 08:44 UTC, mikand commented on unified_planning/io/python_writer.py
> +                out.write(f'type_{cast(_UserType, type).name()} = tm.UserType("{cast(_UserType, type).name()}")\n')
@Framba-Luca I tried the following and it seems to work on mypy:
```diff
diff --git a/unified_planning/io/python_writer.py b/unified_planning/io/python_writer.py
index 0621ffb..94571e9 100644
--- a/unified_planning/io/python_writer.py
+++ b/unified_planning/io/python_writer.py
@@ -145,10 +145,11 @@ class PythonWriter:
         out.write('tm = env.type_manager\n')
 
         for type in self.problem.user_types(): # define user_types
-            if cast(_UserType, type).father() is None:
-                out.write(f'type_{cast(_UserType, type).name()} = tm.UserType("{cast(_UserType, type).name()}")\n')
+            utype = cast(_UserType, type)
+            if utype.father() is None:
+                out.write(f'type_{utype.name()} = tm.UserType("{utype.name()}")\n')
             else:
-                out.write(f'type_{cast(_UserType, type).name()} = tm.UserType("{cast(_UserType, type).name()}", type_{cast(_UserType, cast(_UserType, type).father()).name()})\n') 
+                out.write(f'type_{utype.name()} = tm.UserType("{utype.name()}", type_{cast(_UserType, utype.father()).name()})\n') 
 
         for f in self.problem.fluents(): # define fluents
             params = ', '.join(_print_python_type(p) for p in f.signature())
```

2022-03-01 14:45 UTC, alvalentini commented on unified_planning/io/python_writer.py
> +                out.write(f'problem.add_timed_goal(timing={_convert_interval(i)}, goal={converter.convert(g)})\n')
```suggestion
                out.write(f'problem.add_timed_goal(interval={_convert_interval(i)}, goal={converter.convert(g)})\n')
```
or
```suggestion
                out.write(f'problem.add_timed_goal({_convert_interval(i)}, {converter.convert(g)})\n')
```

2022-03-10 07:50 UTC, mikand approved these changes

2022-03-10 07:50 UTC, merged