Added a name to the fluent parameters
aiplan4eu/unified-planning pull request #90
Opened 2022-02-28 14:18 UTC by Framba-Luca

2022-03-10 08:06 UTC, mikand requested changes
@Framba-Luca I left some comments to be fixed, but overall it looks good!

2022-03-10 08:06 UTC, mikand commented on unified_planning/model/problem.py
> +            v = domain_item(self, list(fluent.signature().values())[i], rem) #TODO: find a better way
It's pretty easy: in line 427 you can simply iterate on the values ```for i, t in enumerate(fluent.signature().values()):```

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/minimals.py
> +    y = Fluent('y', BoolType(), p1=sem)
```suggestion
    y = Fluent('y', BoolType(), semaphore=sem)
```

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/minimals.py
> +    is_same_obj = Fluent('is_same_obj', BoolType(), p1=Obj, p2=Obj)
```suggestion
    is_same_obj = Fluent('is_same_obj', BoolType(), object1=Obj, object2=Obj)
```

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/minimals.py
> +    y = Fluent('y', BoolType(), p1=sem)
Also in other cases, use meaningful names now that we have them

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/realistic.py
> +    robot_at = Fluent('robot_at', BoolType(), p1=Location)
```suggestion
    robot_at = Fluent('robot_at', BoolType(), pos=Location)
```

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/realistic.py
> +    robot_at = Fluent('robot_at', BoolType(), p1=Location)
Same below

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/examples/testing_variants.py
> +    robot_at = Fluent('robot_at', BoolType(), p1=Location)
Same as before, use meaningful names

2022-03-10 08:06 UTC, mikand commented on unified_planning/test/test_grounder.py
> +        visited = Fluent('at', BoolType(), p1=Location)
Same

2022-03-10 08:13 UTC, alvalentini requested changes

2022-03-10 08:13 UTC, alvalentini commented on unified_planning/model/fluent.py
> +                 signature: Optional[OrderedDict[str, 'unified_planning.model.types.Type']] = None, env: Environment = None, **kwargs):
```suggestion
                 parameters: Optional[OrderedDict[str, 'unified_planning.model.types.Type']] = None, env: Environment = None, **kwargs: 'unified_planning.model.types.Type'):
```

2022-03-11 09:21 UTC, alvalentini approved these changes

2022-03-11 09:29 UTC, merged